# @package _global_
SEED: 12
ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    MAX_SCENE_REPEAT_STEPS: 50000
    SHUFFLE: True
SIMULATOR:
  ACTION_SPACE_CONFIG: v0
  AGENTS: ['AGENT_0']
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 15
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  RGB_SENSOR:
    TYPE: HabitatSimRGBSensor
    WIDTH: 224
    HEIGHT: 224
    HFOV: 90
  DEPTH_SENSOR:
    TYPE: HabitatSimDepthSensor
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    NORMALIZE_DEPTH: True

TASK:
  ACTIONS:
    NO_OP:
      TYPE: NoOpAction
  SUCCESS_DISTANCE: 3.0
  POSSIBLE_ACTIONS: [STOP, MOVE_FORWARD, TURN_LEFT, TURN_RIGHT, NO_OP]
  SENSORS: [
    INSTRUCTION_SENSOR
  ]
  INSTRUCTION_SENSOR_UUID: instruction
  MEASUREMENTS: [
    TOP_DOWN_MAP,
    DISTANCE_TO_GOAL,
    SUCCESS,
    SPL,
    TRAJECTORY_LENGTH,
    ORACLE_SUCCESS,
    ORACLE_NAVIGATION_ERROR
  ]
  SUCCESS:
    SUCCESS_DISTANCE: 3.0
  SPL:
    SUCCESS_DISTANCE: 3.0
  TRAJECTORY_LENGTH:
    TYPE: TrajectoryLength
  ORACLE_SUCCESS:
    TYPE: OracleSuccess
    SUCCESS_DISTANCE: 3.0
  ORACLE_NAVIGATION_ERROR:
    TYPE: OracleNavigationError

DATASET:
  TYPE: R2RVLN-v1
  SPLIT: val_unseen
  SCENES_DIR: /data/vln-dependency/VLN-CE/scene_dataset/
  DATA_PATH: /data/vln-dependency/VLN-CE/datasets/r2r/{split}/{split}.json.gz
